config/routes.rb
Jambox::Application.routes.draw do

  resources :requests

  #dashboard
  match 'dashboard' => 'dashboard#index', :as => :dashboard
  match 'invite' => 'welcome#invite', :as => :invite
  get "dropbox/authorize"
  
  #upload
  match 'upload' => 'dropbox#dir', :as => :upload

  match "dropbox/:path/upload_sample" => 'dropbox#upload_sample'
  
  # get "dropbox/index"
  get "dropbox" => 'dashboard#index'
  post "dropbox/jam"
  post "dropbox/create"
  
  # match 'dropbox/:path' => 'dropbox#dir'
  # match 'dropbox/:path/download' => 'dropbox#download'
  
  root :to => "welcome#index"
end

app/models/jam.rb
class Jam < ActiveRecord::Base
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def login_required
    if session[:dropbox_session]
      dropbox_session = get_dropbox_session()
      if dropbox_session.authorized?
        return true
      end
    end
    flash[:warning]='Please login to continue'
    session[:return_to]=request.request_uri
    redirect_to :controller => "dropbox", :action => "authorize"
    return false 
  end
  
  def get_dropbox_session
    Dropbox::Session.deserialize(session[:dropbox_session])
  end
  
  def files(dropbox_session, dir_path)
    @jam_files = dropbox_session.list dir_path, :mode => :dropbox
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :login_required, :except => ['authorize']
  
  def index
    account = get_dropbox_session().account()
    
    @dir_path = "/samples"
    @files = files(get_dropbox_session(), @dir_path)
    @title = "Dashboard"
  end

end

app/controllers/dropbox_controller.rb
class DropboxController < ApplicationController
  before_filter :login_required, :except => ['authorize']

  # ROOT_DIR = "/tmp/jambox/"

  def index
    account = get_dropbox_session().account()
    
    @dir_path = "/samples"
    @files = files(get_dropbox_session(), @dir_path)
    @title = "Dashboard"
  end
  
  def create
    path = "/"+params[:create]
    dropbox_session = get_dropbox_session()
    begin
      dropbox_session.create_folder path, :mode => :dropbox
      dropbox_session.create_folder path, :mode => :dropbox
    rescue Dropbox::FileExistsError
    end
    
    account = get_dropbox_session().account()
    
    puts path
    Jam.create(:uid => account.uid, :dir => "/"+path)
    
    redirect_to :controller => 'dropbox', :action => 'dir', :path => path
  end
  
  def dir
    @dir_path = "/samples"
    @files = files(get_dropbox_session(), @dir_path)
  end
  
  def authorize
    if params[:oauth_token] then
      dropbox_session = get_dropbox_session()
      dropbox_session.authorize(params)
      session[:dropbox_session] = dropbox_session.serialize # re-serialize the authenticated session

      redirect_to dashboard_url
    else
      dropbox_session = Dropbox::Session.new('gaos6hoy4sbfmbl', 'cm8r1sbmfttpmi0')
      session[:dropbox_session] = dropbox_session.serialize
      redirect_to dropbox_session.authorize_url(:oauth_callback => url_for(:action => 'authorize'))
    end
  end

  def upload_sample
    dropbox_session = get_dropbox_session()
    if request.method == "POST" then
      dropbox_session.upload params[:file], params[:path], :mode => :dropbox
      redirect_to(:action => 'index')
    else
      @dir_path = params[:path]
      @files = files(dropbox_session, @dir_path)
      
      render :action => :dir
    end
  end
  
  def jam
    account = get_dropbox_session().account()
    jam = params["/samples/" + :dir]
    
    Jam.create(:uid => account.uid, :dir => jam)
    render :text => "OK"
  end
  
  def download
    dir_path = params[:path]
    
    pid = fork do
      FileUtils.mkdir_p dir_path

      dropbox_session = get_dropbox_session()
      files = files(dropbox_session, dir_path)
      files.each do | file |
  puts "downloading "+file.path
        file_contents = dropbox_session.download file.path, :mode => :dropbox
  puts "downloaded, now writing to "+file.path
        File.open(file.path, 'wb') do |f| f.write(file_contents) end
  puts "done"
      end
    end

    Process.detach(pid)
    render :text => "OK"
  end
  
  # idea
  #   def music(dropbox_session, dir_path)
  #     music = []
  #     jam_files = dropbox_session.list 'music', :mode => :dropbox
  #     jam_files.each do | file | 
  # puts file.path
  #       files << file if ! file.is_dir and file.path =~ /\.(mp3)$/
  #     end
  #     return files
  #   end
 end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # GET /requests
  # GET /requests.xml
  def index
    @requests = Request.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @requests }
    end
  end

  # GET /requests/1
  # GET /requests/1.xml
  def show
    @request = Request.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @request }
    end
  end

  # GET /requests/new
  # GET /requests/new.xml
  def new
    @request = Request.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @request }
    end
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /requests
  # POST /requests.xml
  def create
    @request = Request.new(params[:request])

    respond_to do |format|
      if @request.save
        format.html { redirect_to(@request, :notice => 'Request was successfully created.') }
        format.xml  { render :xml => @request, :status => :created, :location => @request }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.xml
  def update
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to(@request, :notice => 'Request was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @request.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.xml
  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to(requests_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    render :layout => 'home'
  end
  
  def invite
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dropbox_helper.rb
module DropboxHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.haml
#files
  %h2 Files in the Box
  %ul
  - @files.each do |file|
    %li= link_to file.path[@dir_path.length+2..-1], "#"

app/views/dropbox/authorize.html.erb
<h1>Dropbox#authorize</h1>
<p>Find me in app/views/dropbox/authorize.html.erb</p>

app/views/dropbox/dir.html.erb
<div id="uploadsample">
  <%= form_tag({:action => :upload_sample, :path => @dir_path}, :multipart => true) do %>

  <%= file_field_tag 'file' %>

  <%= submit_tag("Upload Sample") %>
  <% end %>
</div>

<div id="files">
<ul>
<% @files.each do |file| %>
    <li><%= file.path[@dir_path.length+2..-1] %></li>
<% end %>
</ul>
</div>

<script type="text/javascript">
  downloadFiles('<%=@dir_path%>');
</script>

app/views/dropbox/index.html.erb
<div id="files">
  <h2>Files in the Box</h2>
<ul>
<% @files.each do |file| %>
    <li><%= link_to file.path[@dir_path.length+2..-1], "#" %></li>
<% end %>
</ul>
</div>

app/views/dropbox/upload.html.erb
<%= form_tag({:action => :upload}, :multipart => true) do %>

<%= file_field_tag 'file' %>

<%= submit_tag("Upload") %>
<% end %>

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en-US", "xml:lang" => "en-US", :xmlns => "http://www.w3.org/1999/xhtml" }
  %head
    %meta{ 'http-equiv' => "content-type", :content => "text/html; charset=utf-8" }
    %meta{ :name => "Author", :content => "Lance Ennen" }
    %meta{ :name => "viewport", :content => "width=1024" }
    %title= 'DropBoxMusic.info - ' + @title ||= "Welcome"
    %meta{ :name => "Keywords", :content => "DropBoxMusic.info" }
    %meta{ :name => "Description", :content => "DropBoxMusic.info"}
    = stylesheet_link_tag 'compiled/main.css'
    = stylesheet_auto_include_tags
    /%link{ :rel => "shortcut icon", :href => "" }
  %body
    #container
      #header
        %h1= link_to "DropBoxMusic.info", dashboard_url
        #menu
          %ul
            %li= link_to 'Dashboard', dashboard_url
            %li= link_to 'Upload Music', upload_url
            %li= link_to 'Request Music', requests_url
            %li= link_to 'Profile', "#"
            %li= link_to 'Logout', "#"
        #wrapper
          - if flash[:notice]
            #notice
              %p= flash[:notice]
          - if flash[:error]
            #error
              %p= flash[:error]
          = yield
  = javascript_include_tag 'jquery', 'rails', 'application'
  = javascript_auto_include_tags

app/views/layouts/home.html.haml
!!! 5
%html{ :lang => "en-US", "xml:lang" => "en-US", :xmlns => "http://www.w3.org/1999/xhtml" }
  %head
    %meta{ 'http-equiv' => "content-type", :content => "text/html; charset=utf-8" }
    %meta{ :name => "Author", :content => "Lance Ennen" }
    %meta{ :name => "viewport", :content => "width=1024" }
    %title= 'DropBoxMusic.info - ' + @title ||= "Welcome"
    %meta{ :name => "Keywords", :content => "DropBoxMusic.info" }
    %meta{ :name => "Description", :content => "DropBoxMusic.info"}
    = stylesheet_link_tag 'compiled/main.css'
    = stylesheet_auto_include_tags
    /%link{ :rel => "shortcut icon", :href => "" }
  %body
    .container_12
      - if flash[:notice]
        #notice
          %p= flash[:notice]
      - if flash[:error]
        #error
          %p= flash[:error]
      = yield
  = javascript_include_tag 'jquery', 'application'
  = javascript_auto_include_tags

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :song %><br />
    <%= f.text_field :song %>
  </div>
  <div class="field">
    <%= f.label :done %><br />
    <%= f.check_box :done %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1>Listing requests</h1>

<table>
  <tr>
    <th>Artist</th>
    <th>Song</th>
    <th>Done</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @requests.each do |request| %>
  <tr>
    <td><%= request.artist %></td>
    <td><%= request.song %></td>
    <td><%= request.done %></td>
    <td><%= link_to 'Show', request %></td>
    <td><%= link_to 'Edit', edit_request_path(request) %></td>
    <td><%= link_to 'Destroy', request, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Artist:</b>
  <%= @request.artist %>
</p>

<p>
  <b>Song:</b>
  <%= @request.song %>
</p>

<p>
  <b>Done:</b>
  <%= @request.done %>
</p>


<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>

app/views/welcome/index.html.haml
#welcome   
  = image_tag("mrt.gif", :style => "text-align:center;")
  %h1 DropBoxMusic.info
  %p Welcome to DropBoxMusic.info. This is an invite only site.
  .links
    %ul
      %li= link_to "Enter", dashboard_path
      %li= link_to "Request Invite", root_path, :id => "request"
 

app/views/welcome/invite.html.haml
%h2 Coming Soon